AIRTABLE_PAT = "patPi0EkkyhssdmHm.07c7724fe2b05f2758bf0e4b2a278da2b8c9be08b91b019c1ac6c240fab92ffd"
BASE_ID = "app87RFuOmswJXa9Q"
TABLE_NAME = "User table"
EMAIL_ADDRESS = "ijehjoel1@gmail.com"
EMAIL_APP_PASSWORD = "jttf yacy tqvj ghcn"
MESSAGES_TABLE = "Messages"
CLOUD_NAME= "deaprngfl"
API_KEY= "186753967323192"
API_SECRET= "mlrPlA_KihWJhC00YD-cYwWkqjM"